# Generated by Django 5.1.7 on 2025-03-12 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('social_security', 'Social Security'), ('private', 'Private')], max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('emergency', 'Emergency')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phones', models.ManyToManyField(blank=True, to='qrSalvavidas.phone')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qrSalvavidas.role')),
            ],
        ),
        migrations.CreateModel(
            name='QRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrSalvavidas.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('age', models.CharField(max_length=3)),
                ('personal_phone', models.CharField(max_length=20)),
                ('retired', models.BooleanField(default=False)),
                ('blood_type', models.CharField(max_length=10)),
                ('medication_allergies', models.TextField(blank=True, null=True)),
                ('takes_medication', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('patient_status', models.CharField(blank=True, max_length=255, null=True)),
                ('organ_donor', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('ambulance_service', models.ManyToManyField(blank=True, to='qrSalvavidas.ambulanceservice')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL)),
                ('medical_coverage', models.ManyToManyField(blank=True, to='qrSalvavidas.medicalcoverage')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_persons', to=settings.AUTH_USER_MODEL)),
                ('company_phones', models.ManyToManyField(blank=True, related_name='company_phones', to='qrSalvavidas.phone')),
                ('phones', models.ManyToManyField(blank=True, to='qrSalvavidas.phone')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qrSalvavidas.qrdata')),
            ],
        ),
    ]
