# Generated by Django 5.1.7 on 2025-03-22 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrSalvavidas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='user',
        ),
        migrations.AddField(
            model_name='qrdata',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_data', to='qrSalvavidas.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='medicalcoverage',
            unique_together={('type', 'name')},
        ),
    ]
