# Generated by Django 5.1.7 on 2025-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrSalvavidas', '0002_remove_person_qr_remove_qrdata_user_qrdata_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
