# Generated by Django 5.1.7 on 2025-03-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrSalvavidas', '0003_person_lastname_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
