# Generated by Django 5.1.7 on 2025-03-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrSalvavidas', '0006_person_country_person_nationality_person_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
