# Generated by Django 5.1.7 on 2025-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrSalvavidas', '0009_person_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de urgencia'),
        ),
        migrations.AddField(
            model_name='person',
            name='hospital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital donde se atiende'),
        ),
        migrations.AddField(
            model_name='person',
            name='insurance_plan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° de afiliado y plan'),
        ),
    ]
