# Generated by Django 5.1.7 on 2025-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrSalvavidas', '0010_person_emergency_contact_phone_person_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='insurance_plan',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='N° de afiliado y plan'),
        ),
    ]
