# Generated by Django 5.1.7 on 2025-03-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='read_qr',
            field=models.BooleanField(default=False),
        ),
    ]
